#!/bin/bash

# CallAssist Complete Screenshot Capture
# Interactive guide to capture all 8 App Store screenshots

set -e

DEVICE_UDID="6ECF589D-26A3-49D7-8A2D-C642466146A2"
SCREENSHOTS_DIR="/Users/andrewleone/projects/CallAssist/Screenshots/6.7-inch-raw"

echo "📸 CallAssist Screenshot Capture Wizard"
echo "========================================"
echo ""
echo "This script will guide you through capturing all 8 screenshots."
echo "The app is already running in the simulator!"
echo ""
echo "Press ENTER after completing each step..."
echo ""

# Screenshot 1
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Screenshot 1: New Appointment Form"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actions:"
echo "  1. Look at the simulator - you should see the New Appointment screen"
echo "  2. Fill in these details:"
echo "     • Business Name: Downtown Dental"
echo "     • Phone Number: (555) 123-4567"
echo "     • Service: Teeth cleaning and annual checkup"
echo ""
read -p "Press ENTER when form is filled and ready to capture..."
xcrun simctl io "$DEVICE_UDID" screenshot "$SCREENSHOTS_DIR/01-new-appointment.png"
echo "✅ Screenshot 1 saved!"
echo ""

# Screenshot 2
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Screenshot 2: Calendar Selection"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actions:"
echo "  1. Tap 'Select Available Times'"
echo "  2. Select 2-3 time slots (e.g., tomorrow 2-4pm, Friday 10am-12pm)"
echo "  3. Times should be highlighted in blue"
echo ""
read -p "Press ENTER when times are selected..."
xcrun simctl io "$DEVICE_UDID" screenshot "$SCREENSHOTS_DIR/02-calendar-selection.png"
echo "✅ Screenshot 2 saved!"
echo ""

# Screenshot 3
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Screenshot 3: Listen In Option"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actions:"
echo "  1. Go back to the main form (data should still be there)"
echo "  2. Scroll down to 'Call Options'"
echo "  3. Toggle 'Listen In' to ON (should turn blue)"
echo "  4. Show the complete form ready to place call"
echo ""
read -p "Press ENTER when Listen In is enabled..."
xcrun simctl io "$DEVICE_UDID" screenshot "$SCREENSHOTS_DIR/03-ready-to-call.png"
echo "✅ Screenshot 3 saved!"
echo ""

# Screenshot 4
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Screenshot 4: Call in Progress"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actions:"
echo "  1. Tap 'Place Call' button"
echo "  2. Wait for call status screen to appear"
echo "  3. Capture when status shows 'In Progress' or 'Ringing...'"
echo "     (with animated phone icon)"
echo ""
echo "⚠️  Note: This will actually initiate a real call!"
echo ""
read -p "Press ENTER when call status screen is showing..."
xcrun simctl io "$DEVICE_UDID" screenshot "$SCREENSHOTS_DIR/04-call-in-progress.png"
echo "✅ Screenshot 4 saved!"
echo ""

# Screenshot 5
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Screenshot 5: Listen In Feature"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actions:"
echo "  1. When the call connects, Listen In sheet should open automatically"
echo "  2. Shows audio visualization with animated circles"
echo "  3. 'Transfer to Me' and 'Stop Listening' buttons visible"
echo ""
read -p "Press ENTER when Listen In screen is showing..."
xcrun simctl io "$DEVICE_UDID" screenshot "$SCREENSHOTS_DIR/05-listen-in.png"
echo "✅ Screenshot 5 saved!"
echo ""

# Screenshot 6
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Screenshot 6: Call History"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actions:"
echo "  1. Close the call (tap 'Close' or wait for completion)"
echo "  2. Navigate to 'History' tab at the bottom"
echo "  3. Should show list of completed appointments"
echo ""
read -p "Press ENTER when History tab is showing..."
xcrun simctl io "$DEVICE_UDID" screenshot "$SCREENSHOTS_DIR/06-call-history.png"
echo "✅ Screenshot 6 saved!"
echo ""

# Screenshot 7
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Screenshot 7: Purchase Minutes"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actions:"
echo "  1. Tap the minute balance widget (top right)"
echo "  2. Purchase Minutes screen should show 4 packages:"
echo "     - 25 Minutes: $14.99"
echo "     - 100 Minutes: $49.99"
echo "     - 250 Minutes: $99.99 (Best Value)"
echo "     - 500 Minutes: $174.99"
echo ""
read -p "Press ENTER when Purchase screen is showing..."
xcrun simctl io "$DEVICE_UDID" screenshot "$SCREENSHOTS_DIR/07-purchase-minutes.png"
echo "✅ Screenshot 7 saved!"
echo ""

# Screenshot 8 (Optional)
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📱 Screenshot 8: Call Results (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Actions:"
echo "  1. Go back to History tab"
echo "  2. Tap on a completed appointment"
echo "  3. Should show results with transcript"
echo ""
read -p "Press ENTER to capture (or Ctrl+C to skip)..."
xcrun simctl io "$DEVICE_UDID" screenshot "$SCREENSHOTS_DIR/08-call-results.png" 2>/dev/null || echo "Skipped"
echo "✅ Screenshot 8 saved (if available)!"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎉 All Screenshots Captured!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📁 Screenshots saved to:"
echo "   $SCREENSHOTS_DIR/"
echo ""
echo "📊 Screenshot count:"
ls -1 "$SCREENSHOTS_DIR"/*.png 2>/dev/null | wc -l | xargs echo "   "
echo ""
echo "🎨 Next Steps:"
echo "  1. Review screenshots: open $SCREENSHOTS_DIR"
echo "  2. Add captions (optional): ./add-captions.sh"
echo "  3. Upload to App Store Connect"
echo ""
echo "✅ Done!"
